#!/usr/bin/env bash

TIME=${date +"%x %r %Z"} #establish time
touch $3


echo $TIME > $3

for i in $1/*
do
$2 $i
	if [  "$?" = "0" ]; then
		echo "$2 $i successful" >> $3
	else
		echo "$2 $i failed" >> $3
	fi

done